### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sergrodrig** [mattsta/getTV#1]
Hi. I'm not sure but i think that in line 83 of getTv.py it says:

`with file("output.html", "w") as err: err.write(r.text)`

but it should say:

`with open("output.html", "w") as err: err.write(r.text)`

Regards.

**Comment by mattsta** [comment]
Thanks for the note!

I just pushed some updates I had which fixed that too.

Sadly we are hitting that error because the tv API has been offline for about two weeks now. If the API remains unavailable much longer, we should just scrape the website directly since it remains stable even though their underlying JSON endpoint isn't stable. 🤷‍♂️
